# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 437efc54e5c4d38af831dca9c63f71899bfcb9e29e6ca80b4603045157e056e3aded942ac33cfb524c250efa7b24e611e74447064c141a5b94f1558ec4987e5b

test:
  secret_key_base: bed9a9b26697e80a03d0d0e61af0d35117969ca7b58c043640c2b88056ee808e7f163669ee4beea02ef63edb20a7a54c85c62c668722d3cbb11ca5e607b3b492

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: d9f5c9d3c1fa744e29fc3bdf339f0bd777238b4f0f43d52be707e5a23452b27e4bbb42c30aab54fa897ff85141e8c71a42eb86ab5abaf54f3bcae1fedcbd162b
